# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000

create_project -in_memory -part xc7a35ticpg236-1L
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Xilinx/1/project_1ab7/project_1ab7.cache/wt [current_project]
set_property parent.project_path C:/Xilinx/1/project_1ab7/project_1ab7.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  C:/Xilinx/1/project_1ab7/project_1ab7.srcs/sources_1/new/lab7_fsm.v
  C:/Xilinx/1/project_1ab7/project_1ab7.srcs/sources_1/new/lab7_datapath.v
  C:/Xilinx/1/project_1ab7/project_1ab7.srcs/sources_1/new/lab7_top.v
}
read_xdc C:/Xilinx/1/project_1ab7/project_1ab7.srcs/constrs_1/imports/new/lab6_con.xdc
set_property used_in_implementation false [get_files C:/Xilinx/1/project_1ab7/project_1ab7.srcs/constrs_1/imports/new/lab6_con.xdc]

catch { write_hwdef -file lab7_top.hwdef }
synth_design -top lab7_top -part xc7a35ticpg236-1L
write_checkpoint -noxdef lab7_top.dcp
catch { report_utilization -file lab7_top_utilization_synth.rpt -pb lab7_top_utilization_synth.pb }
