set_property IOSTANDARD LVCMOS33 [get_ports {vga_b[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_b[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_b[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_b[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_g[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_g[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_g[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_g[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_r[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_r[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_r[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_r[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports hsync]
set_property IOSTANDARD LVCMOS33 [get_ports rst]
set_property IOSTANDARD LVCMOS33 [get_ports vsync]
set_property PACKAGE_PIN N19 [get_ports {vga_r[3]}]
set_property PACKAGE_PIN J19 [get_ports {vga_r[2]}]
set_property PACKAGE_PIN H19 [get_ports {vga_r[1]}]
set_property PACKAGE_PIN G19 [get_ports {vga_r[0]}]
set_property PACKAGE_PIN D17 [get_ports {vga_g[3]}]
set_property PACKAGE_PIN G17 [get_ports {vga_g[2]}]
set_property PACKAGE_PIN H17 [get_ports {vga_g[1]}]
set_property PACKAGE_PIN J17 [get_ports {vga_g[0]}]
set_property PACKAGE_PIN J18 [get_ports {vga_b[3]}]
set_property PACKAGE_PIN K18 [get_ports {vga_b[2]}]
set_property PACKAGE_PIN L18 [get_ports {vga_b[1]}]
set_property PACKAGE_PIN N18 [get_ports {vga_b[0]}]
set_property PACKAGE_PIN P19 [get_ports hsync]
set_property PACKAGE_PIN R19 [get_ports vsync]
set_property PACKAGE_PIN W5 [get_ports clk]
set_property PACKAGE_PIN U18 [get_ports rst]

set_property PACKAGE_PIN U16 [get_ports {led1[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {led1[0]}]
set_property PACKAGE_PIN E19 [get_ports {led1[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {led1[1]}]
set_property PACKAGE_PIN U19 [get_ports {led2[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {led2[0]}]
set_property PACKAGE_PIN V19 [get_ports {led2[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {led2[1]}]
    
    set_property PACKAGE_PIN N17 [get_ports Sound]
    set_property IOSTANDARD LVCMOS33 [get_ports Sound]
    
    set_property PACKAGE_PIN M18 [get_ports scl]
    set_property IOSTANDARD LVCMOS33 [get_ports scl]
    
    set_property PACKAGE_PIN K17 [get_ports sda]
    set_property IOSTANDARD LVCMOS33 [get_ports sda]
    
    set_property PACKAGE_PIN R2 [get_ports rst]
    set_property IOSTANDARD LVCMOS33 [get_ports rst]
    
    set_property PACKAGE_PIN T1 [get_ports Mode]
    set_property IOSTANDARD LVCMOS33 [get_ports Mode]
    
    set_property PACKAGE_PIN T18 [get_ports PlusIn]
    set_property IOSTANDARD LVCMOS33 [get_ports PlusIn]
    
    set_property PACKAGE_PIN U17 [get_ports MinusIn]
    set_property IOSTANDARD LVCMOS33 [get_ports MinusIn]
    
    set_property PACKAGE_PIN L1 [get_ports act]
    set_property IOSTANDARD LVCMOS33 [get_ports act]
    
    set_property PACKAGE_PIN N3 [get_ports Steping[0]]
    set_property IOSTANDARD LVCMOS33 [get_ports  Steping[0]]
    
    set_property PACKAGE_PIN P3 [get_ports  Steping[1]]
    set_property IOSTANDARD LVCMOS33 [get_ports  Steping[1]]
    
    set_property PACKAGE_PIN U3 [get_ports  Steping[2]]
    set_property IOSTANDARD LVCMOS33 [get_ports Steping[2]]
    
    set_property PACKAGE_PIN U18 [get_ports  little]
    set_property IOSTANDARD LVCMOS33 [get_ports little]