# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Xilinx/1/Project/project_display_module/project_vga_logo.srcs/sources_1/ip/dcm_25m/dcm_25m.xci
# IP: The module: 'dcm_25m' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Xilinx/1/Project/project_display_module/project_vga_logo.srcs/sources_1/ip/dcm_25m/dcm_25m_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'dcm_25m'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/Xilinx/1/Project/project_display_module/project_vga_logo.srcs/sources_1/ip/dcm_25m/dcm_25m.xdc
# XDC: The top module name and the constraint reference have the same name: 'dcm_25m'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/Xilinx/1/Project/project_display_module/project_vga_logo.srcs/sources_1/ip/dcm_25m/dcm_25m_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dcm_25m'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# IP: C:/Xilinx/1/Project/project_display_module/project_vga_logo.srcs/sources_1/ip/dcm_25m/dcm_25m.xci
# IP: The module: 'dcm_25m' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Xilinx/1/Project/project_display_module/project_vga_logo.srcs/sources_1/ip/dcm_25m/dcm_25m_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'dcm_25m'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/Xilinx/1/Project/project_display_module/project_vga_logo.srcs/sources_1/ip/dcm_25m/dcm_25m.xdc
# XDC: The top module name and the constraint reference have the same name: 'dcm_25m'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/Xilinx/1/Project/project_display_module/project_vga_logo.srcs/sources_1/ip/dcm_25m/dcm_25m_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dcm_25m'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
